name: 'Changes related to main or pull requests'
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test-code:
    runs-on: ubuntu-latest
    container: composer:2
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --no-progress

    - name: Check coding standard
      run: ./vendor/bin/php-cs-fixer fix --dry-run

    - name: Run static analysis
      run: ./vendor/bin/phpstan

    - name: Run test suite
      run: ./vendor/bin/phpunit
