name: 'Changes related to main or pull requests'
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: pcov
        php-version: '8.2'

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Check coding standard
      run: ./vendor/bin/php-cs-fixer fix --dry-run

    - name: Run static analysis
      run: ./vendor/bin/phpstan --no-progress

    - name: Run test suite
      run: ./vendor/bin/phpunit --no-progress
